### ISSUE TITLE
Codepen doesn't work correctly on first exercise

### ISSUE THREAD

**Issue by 17twenty** [Microsoft/frontend-bootcamp#106]
![image](https://user-images.githubusercontent.com/379176/54007554-84d64900-41b6-11e9-8098-bd8565ac96b3.png)

The above console errors is thrown out when trying to use the first demo at https://microsoft.github.io/frontend-bootcamp/step1-01/exercise/ -- am I missing a trick?

**Comment by HarshCic** [comment]
Can you provide some more information..
Note that CodePen takes care of the `HTML` and `Body` tags, so you can simply start with the content

**Comment by 17twenty** [comment]
Totally.
What information do you need?

I ran the demo from GitHub and the codepen failed to render any content
when modified and it looks like it's a JS issue.

**Comment by HrBDev** [comment]
I have got the same issue it works on other exercises but the first one is broken.

**Comment by dannyjr894** [comment]
She worked at BofA  and she had my account open on her computer I think that's why happened u think

**Comment by micahgodbolt** [comment]
odd that the JS one doesn't work for some. #108 moved it into css, that should be less problematic.
