### ISSUE TITLE
Can't load CodePen iFrames on Chrome, Firefox, or Brave

### ISSUE THREAD

**Issue by aaronjlemon** [Microsoft/frontend-bootcamp#120]
Codepen iFrame won't load on Chrome and Brave due to X-Frame-Options.

Error: Refused to display 'https://codepen.io/embed/prefill/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Firefox loads blank page with no error messages.

**Comment by micahgodbolt** [comment]
codepen was going through some nasty DDOS attacks the other day. give it another try. It appears to be working for me now.

**Comment by aaronjlemon** [comment]
Sorry for the delay. I've retested this and confirm Codepen is working on Brave, Chrome, and Firefox.
