### ISSUE TITLE
Online community 

### ISSUE THREAD

**Issue by Ochuwa-sophie** [Microsoft/frontend-bootcamp#122]
I came across this tutorial a few weeks ago and it has been very helpful.
My problem though is that I was wondering if there is an online community to complement this.

**Comment by micahgodbolt** [comment]
What did you have in mind? I don't think Ken and I were thinking of turning this into dev.to, or creating a large brand behind it. We were excited about creating approachable content and happy that people are coming across it and learning from it.

**Comment by Ochuwa-sophie** [comment]
Okay. I actually thought it was sort of an online bootcamp.
I love it nonetheless.
Thank you.
