### ISSUE TITLE
Empty result in embedded CodePen for step1-04 

### ISSUE THREAD

**Issue by hwellmann** [Microsoft/frontend-bootcamp#123]
Opening http://localhost:8080/step1-04/demo in my local build, the Result panel is empty instead of displaying `Hello World`.

The same is true for 
https://microsoft.github.io/frontend-bootcamp/step1-04/demo/

After changing
````
<pre data-lang="javascript">
````
to
````
<pre data-lang="babel">
````
the demo works as expected.

**Comment by micahgodbolt** [comment]
Its working now. Codepen had some issues recently.
