### ISSUE TITLE
React intro demo link goes to 404

### ISSUE THREAD

**Issue by apelliciari** [Microsoft/frontend-bootcamp#19]
This is the link: https://microsoft.github.io/frontend-bootcamp/step1-04/demo/

**Comment by bryanzzhu** [comment]
Where'd you find that link?

It should probably point here: https://github.com/Microsoft/frontend-bootcamp/tree/master/step1-04/demo

**Comment by apelliciari** [comment]
Here https://microsoft.github.io/frontend-bootcamp/

See the image https://i.imgur.com/hb5Yimp.png

**Comment by kenotron** [comment]
@micahgodbolt - I think this is intentional, right? There isn't an index.tsx or anything... just an index.temp. I think that's where you start the demo...

**Comment by micahgodbolt** [comment]
yeah, intentional. I'll update the readme to explain this part. We're starting from scratch!
