### ISSUE TITLE
Step1-03

### ISSUE THREAD

**Issue by carlosk12** [Microsoft/frontend-bootcamp#23]
I'm not sure if this is intended to be like this or I missed something but as I was going through step1-03 yesterday I noticed that in both the demo and the exercise folders the `nav` area is like this in the exercise:

````
<nav class="filter">
     <button class="selected">all</button>
     <button>active</button>
     <button>completed</button>
 </nav>
````

After having finished the exercise I'm comparing my code to the version in the final folder and I notice that the `nav` area has suddenly changed there to this:

```
<nav class="filter">
    <button onclick="filter('all', this)" class="selected">all</button>
    <button onclick="filter('active', this)">active</button>
    <button onclick="filter('completed', this)">completed</button>
</nav>
```

Yet it was nowhere mentioned in both the demo nor the exercise to implement the filter function into the code. Is it supposed to be done in the next step or are maybe some instructions missing ?

**Comment by micahgodbolt** [comment]
Great catch! Really thankful that people are walking through the demo and finding these omissions. I'll add a step in 03 demo to include those filter functions. Also realized I can simplify the function and not require you to pass in a redundant string there.
