### ISSUE TITLE
Missing license files in the repository

### ISSUE THREAD

**Issue by Calinou** [Microsoft/frontend-bootcamp#25]
The README states:

> Microsoft and any contributors grant you a license to the Microsoft documentation and other content
in this repository under the [Creative Commons Attribution 4.0 International Public License](https://creativecommons.org/licenses/by/4.0/legalcode),
see the [LICENSE](https://github.com/Microsoft/frontend-bootcamp/blob/master/LICENSE) file, and grant you a license to any code in the repository under the [MIT License](https://opensource.org/licenses/MIT), see the [LICENSE-CODE](https://github.com/Microsoft/frontend-bootcamp/blob/master/LICENSE-CODE) file.

However, neither `LICENSE` nor `LICENSE-CODE` are present in the repository, so clicking those links will return a 404 error.

**Comment by kenotron** [comment]
Good call!

**Comment by kenotron** [comment]
Fixed!!!
