### ISSUE TITLE
Step 1-03 addTodo Function missing from index.html

### ISSUE THREAD

**Issue by chadcodes0** [Microsoft/frontend-bootcamp#28]
First, thanks for posting this repo. Just a heads up, in step 1-03, addTodo function that is described here is not included in this demo section's index.html file.

I don't know if this is on purpose. Maybe it's an exercise within the demo? But then there's an exercise after the demo section.

**Comment by micahgodbolt** [comment]
Yeah, my plan is to actually walk through and write that (I think :D)

I need to update the readme to walk through it fully. I'll leave this issue to track that work...Thanks!

**Comment by chadcodes0** [comment]
No problem, thanks for creating this. Just curious, are we going to be using the react cli?
