### ISSUE TITLE
Day 2 Step 4 Exercise Link Broken

### ISSUE THREAD

**Issue by Seun-O** [Microsoft/frontend-bootcamp#40]
When you click the exercise link it leads to Github 404 file not found
https://microsoft.github.io/frontend-bootcamp/step2-04/exercise/

**Comment by Seun-O** [comment]
The exercise directory is missing from the gh-pages branch, which is why the link is broken.

**Comment by ecraig12345** [comment]
Thanks for noticing! Looks like this has now been fixed now.
