### ISSUE TITLE
No link for user to move from one exercise step to the next

### ISSUE THREAD

**Issue by sudo-kaizen** [Microsoft/frontend-bootcamp#43]
Unlike the demos where there is a link for the user to move from one demo step to the next, the README.MD files of the exercises do not have a link to help a user navigate from one exercise step to the next exercise step or next demo

**Comment by tktik555333** [comment]
wow

**Comment by micahgodbolt** [comment]
We haven't been using the rendered GitHub readmes in the classes (instead embedding them in each page). I agree there is a value add, but it wasn't high pri as we weren't using them.

**Comment by sudo-kaizen** [comment]
@micahgodbolt  Great! I'll close it now!
