### ISSUE TITLE
Flux diagram link goes to 404

### ISSUE THREAD

**Issue by SergioDiez** [Microsoft/frontend-bootcamp#66]
The Flux Diagram link inside [step2-05 demo](https://github.com/Microsoft/frontend-bootcamp/tree/master/step2-05/demo)  redirects to a 404 page.
The expected link is https://github.com/Microsoft/frontend-bootcamp/blob/master/step2-05/assets/flux.png

**Comment by SergioDiez** [comment]
I created a new PR #73 to fix this

**Comment by kenotron** [comment]
we have it referenced like this i suppose for the sake of ```npm start``` which has a slightly different pathing.
