### ISSUE TITLE
Day 1 Broken Links

### ISSUE THREAD

**Issue by amitdahan** [Microsoft/frontend-bootcamp#75]
There are some broken links that I found:
- ![image](https://user-images.githubusercontent.com/9748762/53698211-4cafbe80-3de2-11e9-91e0-4f05f7ae929d.png)
- ![image](https://user-images.githubusercontent.com/9748762/53698215-56d1bd00-3de2-11e9-9527-48ca9f7ea463.png)
- ![image](https://user-images.githubusercontent.com/9748762/53698237-8b457900-3de2-11e9-8873-80bcbbc70268.png) (Only "Final")

**Comment by Inconite** [comment]
Link to React Intro demo too is not working.

**Comment by micahgodbolt** [comment]
Did lots of changes yesterday. Fixed.
