### ISSUE TITLE
Cannot clone empty node

### ISSUE THREAD

**Issue by rakhi2104** [Microsoft/frontend-bootcamp#8]
In step01-03/final
Creating a new node with an empty list breaks the app.
Cannot find a node with `.todo` when all completed todo items are cleared.

**Comment by kenotron** [comment]
Is this related to #5 ? Can you point to the step

**Comment by rakhi2104** [comment]
In step01-03/final

**Comment by micahgodbolt** [comment]
this is why you don't use raw JS and cloning to write your app :D

**Comment by micahgodbolt** [comment]
As the focus of this step is on writing JS, not writing applications, I'm going to leave this 'bug' in the code and mention it in the docs that this approach is fragile due to this edge case.
